.TH CHECKZOMBIES 1 "Januar 2026" "checkzombies 2.0" "User Commands"
.SH NAME
checkzombies \- Findet und bereinigt Zombie-Prozesse
.SH SYNOPSIS
.B checkzombies
.RB [ OPTION ]...
.SH DESCRIPTION
.B checkzombies
sucht nach Zombie-Prozessen (Status Z/defunct), zeigt PID/PPID/Service-Informationen
und bietet sichere Bereinigungsoptionen mit Signal-Eskalation und systemd-Support.

.SH OPTIONS
.TP
.B \-h, \-\-help
Zeigt diese Hilfe an
.TP
.B \-v, \-\-version
Zeigt Versionsinformation
.TP
.B \-a, \-\-auto
Automatisch alle Zombie-Parent-Prozesse terminieren
.TP
.B \-l, \-\-list
Nur Zombies auflisten (keine Interaktion)
.TP
.B \-w, \-\-watch
Kontinuierliche \[:U00FC]berwachung alle 10 Sekunden
.TP
.B \-f, \-\-force
Erlaubt KILL nach TERM-Timeout (GEF\[:U00C4]HRLICH!). Nicht mit \-\-list kombinierbar.
.TP
.B \-\-no\-unicode
Erzwingt ASCII-Ausgabe (keine Unicode-Symbole)
.TP
.B \-\-log\-file \fIPFAD\fR
Logdatei setzen (Standard: $HOME/checkzombies.log)
.TP
.B \-\-no\-log\-file
Datei-Logging deaktivieren
.TP
.B \-\-log\-syslog
Zus\[:U00E4]tzlich in syslog/journald loggen (via logger)
.TP
.B \-\-log\-level \fILEVEL\fR
Log-Level setzen (DEBUG, INFO, WARN, ERROR)
.TP
.B \-\-
Ende der Optionen

.SH EXIT STATUS
.TP
.B 0
Keine Zombies gefunden oder erfolgreiche Bereinigung
.TP
.B 1
Fehler (z.B. ung\[:U00FC]ltige Option oder interner Fehler)
.TP
.B 2
Zombies gefunden, aber nicht bereinigt (z.B. Nutzer abgebrochen)

.SH BEISPIELE
.IP
checkzombies
.br
Interaktives Men\[:U00FC] mit Zombie-Auswahl (nur bei TTY)
.IP
checkzombies --auto
.br
Automatische Bereinigung aller Zombies
.IP
checkzombies --list | less
.br
Nur Zombie-Liste als Text (bei Pipe ohne Header und ohne Unicode)
.IP
checkzombies --watch
.br
Live-\[:U00DC]berwachung alle 10 Sekunden

.SH FILES
$HOME/checkzombies.log
.br
Logfile mit allen Aktionen

.SH SYSTEMD (OPTIONAL)
Optional enthaltene systemd-Units starten checkzombies im Watch-Modus oder periodisch im Auto-Modus.
Die Installationshilfe liegt in \fIscripts/systemd_install.sh\fR und kopiert die Unit-Files nach
\fI/etc/systemd/system\fR.
Root-Rechte sind erforderlich.

.SH ENVIRONMENT
.TP
.B CHECKZOMBIES_LOG_FILE
Standard-Logdatei \[:U00FC]berschreiben
.TP
.B CHECKZOMBIES_LOG_LEVEL
Default-Log-Level (DEBUG, INFO, WARN, ERROR)
.TP
.B CHECKZOMBIES_LOG_SYSLOG
Syslog-Logging aktivieren (1=ja)

.SH AUTHOR
161sam <find.me@github>

.SH COPYRIGHT
Copyright (C) 2026 161sam
